- name: Install httpd
  hosts: 10.0.17.101
  tasks:
  - name: install php
    yum: name=php state=present
  - name: Install packages
    yum: pkg=httpd state=latest
  - name: install wordpress
    get_url:
      url: http://wordpress.org/latest.tar.gz
      dest: /home/nick-adm
  - name: change file permissions
    ansible.builtin.file:
      path: /var/www/html
      owner: root
      group: root
      mode: '1777'
  - name: unzip wordpress
    unarchive:
      src: /home/nick-adm/latest.tar.gz
      dest: /var/www/html
  - name: move wordpress files
    copy:
      dest: /var/www/html
      src: /var/www/html/wordpress/
      remote_src: yes
  - name: edit httpd config
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      search_string: 'index.html'
      line: DirectoryIndex index.php
  - name: start httpd
    service:
      name: httpd
      state: started
  - name: open firewall port
    firewalld:
      service: http
      permanent: true
      state: enabled
  - name: reload firewall
    service:
      name: firewalld
      state: restarted