
---
# This playbook shows how to parse a csv file
- name: parsecsv
  hosts: 10.0.5.5

  tasks:
  - name: group_file
    command: cat ./groups.txt
    register: groupnames
    delegate_to: 127.0.0.1

  - name: groupnames loop
     #debug:
     #  msg: "{{ item }}"
    win_domain_group:
      name: "{{ item }}"
      path: "OU=Groups,OU=Accounts,OU=blue7,DC=blue7,DC=local"
      scope: global
      state: present
    with_items: "{{ groupnames.stdout_lines }}"

  - name: read csv file
    read_csv:
      path: ./accounts.csv
    register: accounts
    delegate_to: 127.0.0.1

  - name: ansible loop
      #debug:
        #msg: "{{ item.account_name }} - {{ item.group }}"
    win_domain_user:
      name: "{{ item.account_name }}"
      path: "OU=Accounts,OU=blue7,DC=blue7,DC=local"
      password: "{{ item.password }}"
      password_never_expires: yes
      update_password: on_create
      state: present      
      groups: 
        - "{{ item.group }}"
    with_items: "{{ accounts.list }}"

  - name: laa share folder
    win_file:
      path: C:\shares\laa
      state: directory

  - name: smb share
    win_share:
      name: LAA
      path: C:\shares\laa
      list: no
      full: LAA
      deny: HOU,OAK,TOR,CLE,SEA,BAL,TEX,TBA,BOS,KCA,DET,MIN,NYA,MIL,SLN,CHN,ARI,LAN,SFG,NYN,WAS,SDN,PIT,CIN,COL,ATL,MIA,PHI,CHA